import type { Unit, Concept, Edge } from './types';

export const UNITS: Unit[] = [
  { id: 'ch1',  number: 1,  title: 'Solving Linear Systems',        short: 'Linear Systems',   color: '#67a9ff' },
  { id: 'ch2',  number: 2,  title: 'Abstract Vector Spaces',        short: 'Vector Spaces',    color: '#7eb8ff' },
  { id: 'ch3',  number: 3,  title: 'Linear Transformations',        short: 'Transformations',  color: '#95c7ff' },
  { id: 'ch4',  number: 4,  title: 'Bases & Coordinates',           short: 'Bases',            color: '#acd6ff' },
  { id: 'ch5',  number: 5,  title: 'Inner Products & Orthogonality',short: 'Inner Products',   color: '#ffd966' },
  { id: 'ch6',  number: 6,  title: 'Orthogonal Decomposition',      short: 'Orthogonality',    color: '#ffc966' },
  { id: 'ch7',  number: 7,  title: 'Diagonalization & Dynamics',    short: 'Diagonalization',  color: '#ff9e6b' },
  { id: 'ch8',  number: 8,  title: 'Eigenvalue Complexities',       short: 'Eigenvalues+',     color: '#ff8e6b' },
  { id: 'ch9',  number: 9,  title: 'Linear Iterative Systems',      short: 'Iterative',        color: '#b896ff' },
  { id: 'ch10', number: 10, title: 'Singular Value Decomposition',  short: 'SVD',              color: '#a886ff' },
  { id: 'ch11', number: 11, title: 'Principal Component Analysis',  short: 'PCA',              color: '#9876ff' },
  { id: 'ch12', number: 12, title: 'Low Rank Approximation',        short: 'Low Rank',         color: '#6fd49a' },
  { id: 'ch13', number: 13, title: 'Neural Networks',               short: 'Neural Nets',      color: '#4fd6a3' },
];

// All concept nodes. Flagships get full content in concepts/ — everything else is a stub.
export const CONCEPT_NODES: Concept[] = [
  // ── Ch 1: Solving Linear Systems ───────────────────────────────────────────
  { id: 'linear-systems',      unitId: 'ch1', number: '1.1', tier: 'stub',
    title: 'Linear Systems',
    blurb: 'Systems of equations Ax = b — the central computational object of the course.' },
  { id: 'special-matrices',    unitId: 'ch1', number: '1.2', tier: 'stub',
    title: 'Special Matrices',
    blurb: 'Diagonal, triangular, symmetric, and orthogonal matrices and their algebraic properties.' },
  { id: 'row-reduction',       unitId: 'ch1', number: '1.3', tier: 'stub',
    title: 'Row Reduction',
    blurb: 'Transforming a matrix to row echelon form via elementary row operations.' },
  { id: 'inverses',            unitId: 'ch1', number: '1.4', tier: 'stub',
    title: 'Inverses',
    blurb: 'When Ax = b has a unique solution for every b: the inverse matrix A⁻¹.' },
  { id: 'gaussian-elimination',unitId: 'ch1', number: '1.5', tier: 'stub',
    title: 'Gaussian Elimination',
    blurb: 'Systematic row operations for solving linear systems with O(n³) complexity.' },
  { id: 'lu-decomposition',    unitId: 'ch1', number: '1.6', tier: 'stub',
    title: 'LU Decomposition',
    blurb: 'Factoring A = LU as a product of lower and upper triangular matrices.' },
  { id: 'plu-decomposition',   unitId: 'ch1', number: '1.7', tier: 'stub',
    title: 'PLU Decomposition',
    blurb: 'PA = LU factorization with row pivoting for numerical stability.' },
  { id: 'rank-and-conditioning',unitId: 'ch1', number: '1.8', tier: 'stub',
    title: 'Rank & Conditioning',
    blurb: 'How "close to singular" a matrix is, and what that means for solving Ax = b.' },

  // ── Ch 2: Abstract Vector Spaces ───────────────────────────────────────────
  { id: 'vector-space-axioms',   unitId: 'ch2', number: '2.1', tier: 'stub',
    title: 'Vector Space Axioms',
    blurb: 'The eight axioms that define an abstract vector space beyond ℝⁿ.' },
  { id: 'vector-space-examples', unitId: 'ch2', number: '2.2', tier: 'stub',
    title: 'Vector Space Examples',
    blurb: 'Polynomials, functions, and matrices — all vector spaces governed by the same axioms.' },
  { id: 'subspaces',             unitId: 'ch2', number: '2.3', tier: 'stub',
    title: 'Subspaces',
    blurb: 'Subsets of a vector space that are themselves vector spaces under the same operations.' },
  { id: 'span-and-independence', unitId: 'ch2', number: '2.4', tier: 'stub',
    title: 'Span & Independence',
    blurb: 'What vectors can be built from a set, and when no vector in the set is redundant.' },
  { id: 'dimension',             unitId: 'ch2', number: '2.5', tier: 'stub',
    title: 'Dimension',
    blurb: 'The intrinsic size of a vector space — the cardinality of any minimal spanning set.' },

  // ── Ch 3: Linear Transformations ───────────────────────────────────────────
  { id: 'euclidean-transformations',       unitId: 'ch3', number: '3.1', tier: 'stub',
    title: 'Euclidean Transformations',
    blurb: 'Rotations, reflections, and rigid motions of ℝⁿ expressed as matrix multiplication.' },
  { id: 'linear-transformation-defs',     unitId: 'ch3', number: '3.2', tier: 'stub',
    title: 'Linear Transformations',
    blurb: 'Maps between vector spaces that preserve vector addition and scalar multiplication.' },
  { id: 'linear-transformation-examples', unitId: 'ch3', number: '3.3', tier: 'stub',
    title: 'Transformation Examples',
    blurb: 'Differentiation, integration, and projection as linear transformations on function spaces.' },
  { id: 'injective-surjective',           unitId: 'ch3', number: '3.4', tier: 'stub',
    title: 'Injective & Surjective',
    blurb: 'One-to-one and onto: the two ways a linear map can fail to be invertible.' },
  { id: 'image-and-kernel',               unitId: 'ch3', number: '3.5', tier: 'stub',
    title: 'Image & Kernel',
    blurb: 'The output subspace of a linear map and the set of inputs that map to zero.' },
  { id: 'rank-and-nullity',               unitId: 'ch3', number: '3.6', tier: 'stub',
    title: 'Rank-Nullity Theorem',
    blurb: 'The dimensions of image and kernel satisfy rank + nullity = dim(domain).' },
  { id: 'quotients',                      unitId: 'ch3', number: '3.7', tier: 'stub',
    title: 'Quotient Spaces',
    blurb: 'Collapsing a subspace to a single point — the quotient vector space construction.' },
  { id: 'coimage-cokernel',               unitId: 'ch3', number: '3.8', tier: 'stub',
    title: 'Coimage & Cokernel',
    blurb: 'The dual counterparts to image and kernel, completing the four fundamental subspaces.' },
  { id: 'fundamental-theorem',            unitId: 'ch3', number: '3.9', tier: 'stub',
    title: 'Fundamental Theorem',
    blurb: 'The four fundamental subspaces of a linear map and their orthogonal complementarity.' },

  // ── Ch 4: Bases & Coordinates ──────────────────────────────────────────────
  { id: 'bases',               unitId: 'ch4', number: '4.1', tier: 'stub',
    title: 'Bases',
    blurb: 'A minimal spanning set for a vector space — the coordinate system of the space.' },
  { id: 'coordinates',         unitId: 'ch4', number: '4.2', tier: 'stub',
    title: 'Coordinates',
    blurb: 'Representing any vector uniquely as a linear combination of basis vectors.' },
  { id: 'change-of-basis',     unitId: 'ch4', number: '4.3', tier: 'stub',
    title: 'Change of Basis',
    blurb: 'Converting coordinate representations between different bases for the same space.' },
  { id: 'matrix-representations',unitId: 'ch4', number: '4.4', tier: 'stub',
    title: 'Matrix Representations',
    blurb: 'A linear map written as a matrix — but only after choosing bases for domain and codomain.' },
  { id: 'similarity',          unitId: 'ch4', number: '4.5', tier: 'stub',
    title: 'Similarity',
    blurb: 'Two matrices A = P⁻¹BP represent the same linear map in different bases.' },

  // ── Ch 5: Inner Products & Orthogonality ───────────────────────────────────
  { id: 'dot-and-inner-products',  unitId: 'ch5', number: '5.1', tier: 'stub',
    title: 'Dot & Inner Products',
    blurb: 'Measuring length and angle via a symmetric bilinear pairing of vectors.' },
  { id: 'angles-and-orthogonality',unitId: 'ch5', number: '5.2', tier: 'stub',
    title: 'Angles & Orthogonality',
    blurb: 'Perpendicularity, the generalized cosine rule, and the Cauchy-Schwarz inequality.' },
  { id: 'orthonormal-bases',       unitId: 'ch5', number: '5.3', tier: 'stub',
    title: 'Orthonormal Bases',
    blurb: 'Bases where all vectors are unit length and mutually perpendicular — coordinates are projections.' },
  { id: 'gram-schmidt',            unitId: 'ch5', number: '5.4', tier: 'flagship',
    title: 'Gram–Schmidt Process',
    blurb: 'An algorithm to orthogonalize any basis via successive orthogonal projections.' },
  { id: 'adjoints-and-transposes', unitId: 'ch5', number: '5.5', tier: 'stub',
    title: 'Adjoints & Transposes',
    blurb: 'The natural dual of a linear map that respects the inner product structure.' },
  { id: 'orthogonal-transformations',unitId: 'ch5', number: '5.6', tier: 'stub',
    title: 'Orthogonal Transformations',
    blurb: 'Linear maps that preserve all lengths and angles: rotations and reflections.' },
  { id: 'qr-decomposition',        unitId: 'ch5', number: '5.7', tier: 'stub',
    title: 'QR Decomposition',
    blurb: 'Factoring A = QR into an orthogonal Q and upper triangular R via Gram-Schmidt.' },

  // ── Ch 6: Orthogonal Decomposition ─────────────────────────────────────────
  { id: 'orthogonal-complements',       unitId: 'ch6', number: '6.1', tier: 'stub',
    title: 'Orthogonal Complements',
    blurb: 'The subspace of all vectors perpendicular to a given subspace — dim(V) + dim(V⊥) = n.' },
  { id: 'orthogonal-projections',       unitId: 'ch6', number: '6.2', tier: 'stub',
    title: 'Orthogonal Projections',
    blurb: 'The closest point in a subspace to a given vector — computed via Gram-Schmidt.' },
  { id: 'geometric-fundamental-theorem',unitId: 'ch6', number: '6.3', tier: 'stub',
    title: 'Geometric Fundamental Theorem',
    blurb: 'The four fundamental subspaces pair orthogonally — the geometric picture of linear maps.' },
  { id: 'least-squares',               unitId: 'ch6', number: '6.4', tier: 'stub',
    title: 'Least Squares',
    blurb: 'Finding the best approximate solution when Ax = b is inconsistent via orthogonal projection.' },
  { id: 'regularized-least-squares',   unitId: 'ch6', number: '6.5', tier: 'stub',
    title: 'Regularized Least Squares',
    blurb: 'Adding an ℓ₂ penalty to least squares for numerical stability and implicit regularization.' },

  // ── Ch 7: Diagonalization & Dynamics ───────────────────────────────────────
  { id: 'first-order-systems',    unitId: 'ch7', number: '7.1', tier: 'stub',
    title: 'First-Order Systems',
    blurb: 'Systems of ODEs ẋ = Ax — the bridge between linear algebra and dynamics.' },
  { id: 'coupled-systems',        unitId: 'ch7', number: '7.2', tier: 'stub',
    title: 'Coupled Systems',
    blurb: 'When differential equations interact — decoupling via diagonalization.' },
  { id: 'eigenvectors',           unitId: 'ch7', number: '7.3', tier: 'flagship',
    title: 'Eigenvalues & Eigenvectors',
    blurb: "Vectors a transformation stretches but doesn't rotate — the axes of a linear map." },
  { id: 'simple-diagonalization', unitId: 'ch7', number: '7.4', tier: 'stub',
    title: 'Diagonalization',
    blurb: 'Writing A = PDP⁻¹ when A has n independent eigenvectors — simplifying matrix powers.' },
  { id: 'matrix-exponentials',    unitId: 'ch7', number: '7.5', tier: 'stub',
    title: 'Matrix Exponentials',
    blurb: 'Defining eᴬᵗ via diagonalization to solve linear ODEs in closed form.' },
  { id: 'higher-order-equations', unitId: 'ch7', number: '7.6', tier: 'stub',
    title: 'Higher-Order Equations',
    blurb: 'Converting n-th order ODEs to equivalent first-order systems for eigenvector analysis.' },
  { id: 'basis-solutions',        unitId: 'ch7', number: '7.7', tier: 'stub',
    title: 'Basis Solutions',
    blurb: 'The n independent solutions that span the solution space of a linear ODE system.' },

  // ── Ch 8: Eigenvalue Complexities ──────────────────────────────────────────
  { id: 'complex-eigenvalues',  unitId: 'ch8', number: '8.1', tier: 'stub',
    title: 'Complex Eigenvalues',
    blurb: 'Conjugate-pair eigenvalues produce oscillatory dynamics — spirals in phase space.' },
  { id: 'repeated-eigenvalues', unitId: 'ch8', number: '8.2', tier: 'stub',
    title: 'Repeated Eigenvalues',
    blurb: 'Defective matrices where the eigenspace is too small — polynomial growth in dynamics.' },
  { id: 'jordan-form',          unitId: 'ch8', number: '8.3', tier: 'stub',
    title: 'Jordan Normal Form',
    blurb: 'The canonical block-diagonal form for matrices that cannot be fully diagonalized.' },
  { id: 'finding-jordan-form',  unitId: 'ch8', number: '8.4', tier: 'stub',
    title: 'Finding Jordan Form',
    blurb: 'Computing Jordan blocks from the generalized eigenspace chain structure.' },
  { id: 'computing-eigenvalues',unitId: 'ch8', number: '8.5', tier: 'stub',
    title: 'Computing Eigenvalues',
    blurb: 'Numerical methods (QR algorithm, power iteration) for finding eigenvalues in practice.' },

  // ── Ch 9: Linear Iterative Systems ─────────────────────────────────────────
  { id: 'iteration',              unitId: 'ch9', number: '9.1', tier: 'stub',
    title: 'Iteration',
    blurb: 'Applying a matrix repeatedly: xₖ₊₁ = Axₖ and its long-run convergence behavior.' },
  { id: 'dominance-convergence',  unitId: 'ch9', number: '9.2', tier: 'stub',
    title: 'Dominance & Convergence',
    blurb: 'The largest eigenvalue takes over iterated dynamics — geometric convergence rate.' },
  { id: 'perron-frobenius',       unitId: 'ch9', number: '9.3', tier: 'stub',
    title: 'Perron-Frobenius Theorem',
    blurb: 'Positive matrices always have a positive dominant eigenvalue with a positive eigenvector.' },
  { id: 'symmetric-spectra',      unitId: 'ch9', number: '9.4', tier: 'stub',
    title: 'Symmetric Spectra',
    blurb: 'Symmetric matrices always have real eigenvalues and a complete orthogonal eigenbasis.' },
  { id: 'consensus',              unitId: 'ch9', number: '9.5', tier: 'stub',
    title: 'Consensus Dynamics',
    blurb: 'Networks of agents reaching agreement via iterated local averaging.' },

  // ── Ch 10: SVD ─────────────────────────────────────────────────────────────
  { id: 'spheres-ellipsoids', unitId: 'ch10', number: '10.1', tier: 'stub',
    title: 'Spheres & Ellipsoids',
    blurb: 'How a linear transformation deforms the unit sphere into an ellipsoid — geometric intuition for SVD.' },
  { id: 'polar-decomposition', unitId: 'ch10', number: '10.2', tier: 'stub',
    title: 'Polar Decomposition',
    blurb: 'Every invertible matrix A = QS factors as a rotation Q times a symmetric stretch S.' },
  { id: 'svd-form',           unitId: 'ch10', number: '10.3', tier: 'stub',
    title: 'SVD',
    blurb: 'Every matrix factors as A = UΣVᵀ — the singular value decomposition.' },
  { id: 'svd-invariance',     unitId: 'ch10', number: '10.4', tier: 'stub',
    title: 'SVD Invariance',
    blurb: 'Singular values are intrinsic to the linear map, independent of any choice of bases.' },

  // ── Ch 11: PCA ─────────────────────────────────────────────────────────────
  { id: 'covariance',             unitId: 'ch11', number: '11.1', tier: 'stub',
    title: 'Covariance',
    blurb: 'The covariance matrix encodes how data dimensions co-vary — symmetric and positive semidefinite.' },
  { id: 'principal-components',   unitId: 'ch11', number: '11.2', tier: 'stub',
    title: 'Principal Components',
    blurb: 'The eigenvectors of the covariance matrix — directions of maximum variance in data.' },
  { id: 'pca-optimality',         unitId: 'ch11', number: '11.3', tier: 'stub',
    title: 'PCA Optimality',
    blurb: 'PCA gives the best low-dimensional projection of data in terms of preserved variance.' },
  { id: 'pca-preprocessing',      unitId: 'ch11', number: '11.4', tier: 'stub',
    title: 'PCA Preprocessing',
    blurb: 'Centering and normalizing data before PCA to avoid scale-dependent artifacts.' },
  { id: 'statistical-significance',unitId: 'ch11', number: '11.5', tier: 'stub',
    title: 'Statistical Significance',
    blurb: 'Deciding which principal components capture real structure versus sampling noise.' },
  { id: 'beyond-linear-pca',      unitId: 'ch11', number: '11.6', tier: 'stub',
    title: 'Beyond Linear PCA',
    blurb: 'Kernel PCA, autoencoders, and manifold learning for nonlinear dimensionality reduction.' },

  // ── Ch 12: Low Rank Approximation ──────────────────────────────────────────
  { id: 'optimal-low-rank',      unitId: 'ch12', number: '12.1', tier: 'stub',
    title: 'Optimal Low-Rank Approximation',
    blurb: 'The best rank-k approximation to any matrix is given by truncated SVD (Eckart-Young theorem).' },
  { id: 'low-rank-in-practice',  unitId: 'ch12', number: '12.2', tier: 'stub',
    title: 'Low-Rank in Practice',
    blurb: 'Collaborative filtering, image compression, and latent factor models via low-rank structure.' },
  { id: 'scaling-algorithms',    unitId: 'ch12', number: '12.3', tier: 'stub',
    title: 'Scaling Algorithms',
    blurb: 'Randomized and iterative methods for computing low-rank approximations at scale.' },
  { id: 'matrix-completion',     unitId: 'ch12', number: '12.4', tier: 'stub',
    title: 'Matrix Completion',
    blurb: 'Recovering a full matrix from a sparse set of observed entries under low-rank assumptions.' },
  { id: 'robust-factorization',  unitId: 'ch12', number: '12.5', tier: 'stub',
    title: 'Robust Factorization',
    blurb: 'Low-rank plus sparse decomposition for handling outliers and corrupted observations.' },

  // ── Ch 13: Neural Networks ─────────────────────────────────────────────────
  { id: 'beyond-linear',         unitId: 'ch13', number: '13.1', tier: 'stub',
    title: 'Beyond Linearity',
    blurb: "Why neural networks transcend linear algebra — and why linear algebra still underpins them." },
  { id: 'network-architecture',  unitId: 'ch13', number: '13.2', tier: 'stub',
    title: 'Network Architecture',
    blurb: 'Layers and activations as compositions of linear maps with pointwise nonlinearities.' },
  { id: 'backpropagation',       unitId: 'ch13', number: '13.3', tier: 'stub',
    title: 'Backpropagation',
    blurb: 'Computing gradients of a loss function through a network via the chain rule.' },
  { id: 'sgd',                   unitId: 'ch13', number: '13.4', tier: 'stub',
    title: 'Stochastic Gradient Descent',
    blurb: 'Updating network weights using mini-batch gradient estimates of the loss.' },
  { id: 'attention-transformers',unitId: 'ch13', number: '13.5', tier: 'stub',
    title: 'Attention & Transformers',
    blurb: 'The attention mechanism as scaled dot-product of query, key, and value matrices.' },

  // ── Application Nodes ──────────────────────────────────────────────────────
  { id: 'network-flows',       unitId: 'ch1',  number: '1.A',  tier: 'stub', isApplication: true,
    title: 'Network Flows',
    blurb: "Kirchhoff's current law and flow conservation as linear equations on graph incidence matrices." },
  { id: 'graph-topology',      unitId: 'ch3',  number: '3.10', tier: 'stub', isApplication: true,
    title: 'Graph Topology',
    blurb: 'The Fundamental Theorem applied to incidence matrices reveals cycles, components, and Euler’s formula.' },
  { id: 'engineering-signals', unitId: 'ch2',  number: '2.6.1', tier: 'stub', isApplication: true,
    title: 'Engineering Signals',
    blurb: 'Signals are functions of time, function spaces are vector spaces, and engineering operations are linear transformations.' },
  { id: 'linear-differential-equations', unitId: 'ch2',  number: '2.6.2', tier: 'stub', isApplication: true,
    title: 'Linear Differential Equations',
    blurb: 'Solution sets of linear ODEs are vector spaces — and finding them reduces to finding a basis.' },
  { id: 'robotic-kinematics',  unitId: 'ch3',  number: '3.A',  tier: 'stub', isApplication: true,
    title: 'Robotic Kinematics',
    blurb: 'Jacobians and joint transformations linking linear algebra to robotic motion planning.' },
  { id: 'computer-graphics',   unitId: 'ch3',  number: '3.B',  tier: 'stub', isApplication: true,
    title: 'Computer Graphics',
    blurb: 'Homogeneous coordinates and transformation matrices for 3D rotation, scaling, and projection.' },
  { id: 'signal-processing',   unitId: 'ch5',  number: '5.A',  tier: 'stub', isApplication: true,
    title: 'Signal Processing',
    blurb: 'Fourier transforms and filter banks as orthonormal basis decompositions of signals.' },
  { id: 'structural-analysis', unitId: 'ch6',  number: '6.A',  tier: 'stub', isApplication: true,
    title: 'Structural Analysis',
    blurb: 'Forces in trusses and frames modeled by least-squares over underdetermined linear systems.' },
  { id: 'svm',                 unitId: 'ch6',  number: '6.B',  tier: 'stub', isApplication: true,
    title: 'Support Vector Machines',
    blurb: 'Finding the maximum-margin hyperplane as a constrained quadratic program.' },
  { id: 'building-temperature',unitId: 'ch7',  number: '7.A',  tier: 'stub', isApplication: true,
    title: 'Building Temperature Control',
    blurb: 'Heat flow in buildings modeled as a linear dynamical system with matrix exponential solution.' },
  { id: 'vehicle-suspension',  unitId: 'ch7',  number: '7.B',  tier: 'stub', isApplication: true,
    title: 'Vehicle Suspension',
    blurb: 'Coupled mass-spring systems modeled as second-order linear ODEs.' },
  { id: 'power-grid',          unitId: 'ch7',  number: '7.C',  tier: 'stub', isApplication: true,
    title: 'Power Grid Analysis',
    blurb: 'Voltage and current distribution in electrical networks via linear dynamical systems.' },
  { id: 'chemical-networks',   unitId: 'ch7',  number: '7.D',  tier: 'stub', isApplication: true,
    title: 'Chemical Reaction Networks',
    blurb: 'Near-equilibrium reaction kinetics linearized as first-order dynamical systems.' },
  { id: 'quantum-measurement',  unitId: 'ch8',  number: '8.A',  tier: 'stub', isApplication: true,
    title: 'Quantum Measurement',
    blurb: 'Observables as Hermitian matrices with eigenvectors as measurement outcomes and eigenvalues as results.' },
  { id: 'image-segmentation',  unitId: 'ch9',  number: '9.A',  tier: 'stub', isApplication: true,
    title: 'Image Segmentation',
    blurb: 'Spectral clustering using eigenvectors of the graph Laplacian to segment images.' },
  { id: 'spectral-graph-theory',unitId: 'ch9',  number: '9.B',  tier: 'stub', isApplication: true,
    title: 'Spectral Graph Theory',
    blurb: 'Graph connectivity and community structure encoded in eigenvalues of the Laplacian matrix.' },
  { id: 'pagerank',            unitId: 'ch9',  number: '9.C',  tier: 'stub', isApplication: true,
    title: 'PageRank',
    blurb: "Google's web-ranking algorithm as the dominant eigenvector of the stochastic link matrix." },
  { id: 'sensor-networks',     unitId: 'ch9',  number: '9.D',  tier: 'stub', isApplication: true,
    title: 'Sensor Networks',
    blurb: 'Distributed estimation and agreement in networks of sensors using consensus dynamics.' },
  { id: 'text-embeddings',     unitId: 'ch10', number: '10.A', tier: 'stub', isApplication: true,
    title: 'Text Embeddings',
    blurb: 'Representing words and documents as dense vectors via SVD on co-occurrence matrices.' },
  { id: 'tensors',             unitId: 'ch10', number: '10.B', tier: 'stub', isApplication: true,
    title: 'Tensors',
    blurb: 'Higher-order generalizations of matrices for representing multilinear relationships.' },
  { id: 'k-means',             unitId: 'ch11', number: '11.A', tier: 'stub', isApplication: true,
    title: 'K-Means Clustering',
    blurb: 'An alternating projection algorithm for clustering data into k groups.' },
  { id: 'neural-decoding',     unitId: 'ch11', number: '11.B', tier: 'stub', isApplication: true,
    title: 'Neural Decoding',
    blurb: 'Reconstructing stimuli from neural firing rates via linear regression and PCA.' },
  { id: 'eigenfaces',          unitId: 'ch11', number: '11.C', tier: 'stub', isApplication: true,
    title: 'Eigenfaces',
    blurb: 'Representing human faces as linear combinations of principal components for recognition.' },
  { id: 'image-processing',    unitId: 'ch12', number: '12.A', tier: 'stub', isApplication: true,
    title: 'Image Processing',
    blurb: 'Convolutions and SVD-based compression as linear operations on image matrices.' },
  { id: 'latent-semantic-analysis',unitId: 'ch12', number: '12.B', tier: 'stub', isApplication: true,
    title: 'Latent Semantic Analysis',
    blurb: 'Finding hidden topics in text corpora via truncated SVD on the term-document matrix.' },
  { id: 'netflix-prize',       unitId: 'ch12', number: '12.C', tier: 'stub', isApplication: true,
    title: 'Netflix Prize',
    blurb: 'Collaborative filtering for movie recommendations via matrix completion from sparse ratings.' },
  { id: 'anomaly-detection',   unitId: 'ch12', number: '12.D', tier: 'stub', isApplication: true,
    title: 'Anomaly Detection',
    blurb: 'Detecting outliers as points far from the low-rank subspace of normal data.' },
  { id: 'cnns',                unitId: 'ch13', number: '13.A', tier: 'stub', isApplication: true,
    title: 'Convolutional Neural Networks',
    blurb: 'CNNs as banks of learned linear filters applied via structured sparse matrix operations.' },
  { id: 'llms',                unitId: 'ch13', number: '13.B', tier: 'stub', isApplication: true,
    title: 'Large Language Models',
    blurb: 'LLMs built on transformer attention mechanisms — linear algebra at unprecedented scale.' },
];

// MANUAL_EDGES is the editorial skeleton — curated semantic relationships.
// The graph also unions in mention edges (from [[backlinks]] in concept prose) and
// note edges (from user notes). See concepts.index.ts for the union helpers.
export const MANUAL_EDGES: Edge[] = [
  // ── Ch 1 internal ──────────────────────────────────────────────────────────
  { from: 'linear-systems',       to: 'row-reduction',          type: 'prereq' },
  { from: 'linear-systems',       to: 'special-matrices',       type: 'prereq' },
  { from: 'row-reduction',        to: 'gaussian-elimination',   type: 'prereq' },
  { from: 'gaussian-elimination', to: 'lu-decomposition',       type: 'prereq' },
  { from: 'lu-decomposition',     to: 'plu-decomposition',      type: 'prereq' },
  { from: 'inverses',             to: 'lu-decomposition',       type: 'prereq' },
  { from: 'gaussian-elimination', to: 'rank-and-conditioning',  type: 'prereq' },
  { from: 'inverses',             to: 'rank-and-conditioning',  type: 'related' },

  // ── Ch 2 internal ──────────────────────────────────────────────────────────
  { from: 'vector-space-axioms',   to: 'vector-space-examples', type: 'prereq' },
  { from: 'vector-space-axioms',   to: 'subspaces',             type: 'prereq' },
  { from: 'subspaces',             to: 'span-and-independence', type: 'prereq' },
  { from: 'span-and-independence', to: 'dimension',             type: 'prereq' },

  // ── Ch 3 internal ──────────────────────────────────────────────────────────
  { from: 'euclidean-transformations',       to: 'linear-transformation-defs',     type: 'prereq' },
  { from: 'linear-transformation-defs',     to: 'linear-transformation-examples', type: 'prereq' },
  { from: 'linear-transformation-defs',     to: 'injective-surjective',           type: 'prereq' },
  { from: 'linear-transformation-defs',     to: 'image-and-kernel',               type: 'prereq' },
  { from: 'image-and-kernel',               to: 'rank-and-nullity',               type: 'prereq' },
  { from: 'rank-and-nullity',               to: 'fundamental-theorem',            type: 'prereq' },
  { from: 'image-and-kernel',               to: 'quotients',                      type: 'prereq' },
  { from: 'quotients',                      to: 'coimage-cokernel',               type: 'prereq' },
  { from: 'fundamental-theorem',            to: 'coimage-cokernel',               type: 'generalizes' },
  { from: 'fundamental-theorem',            to: 'graph-topology',                 type: 'applies-to' },
  { from: 'image-and-kernel',               to: 'graph-topology',                 type: 'applies-to' },

  // ── Ch 4 internal ──────────────────────────────────────────────────────────
  { from: 'dimension',             to: 'bases',                  type: 'prereq' },
  { from: 'bases',                 to: 'coordinates',            type: 'prereq' },
  { from: 'coordinates',           to: 'change-of-basis',        type: 'prereq' },
  { from: 'change-of-basis',       to: 'matrix-representations', type: 'prereq' },
  { from: 'matrix-representations',to: 'similarity',             type: 'prereq' },

  // ── Ch 5 internal ──────────────────────────────────────────────────────────
  { from: 'dot-and-inner-products',  to: 'angles-and-orthogonality',  type: 'prereq' },
  { from: 'angles-and-orthogonality',to: 'orthonormal-bases',         type: 'prereq' },
  { from: 'orthonormal-bases',       to: 'gram-schmidt',              type: 'prereq' },
  { from: 'gram-schmidt',            to: 'qr-decomposition',          type: 'prereq' },
  { from: 'qr-decomposition',        to: 'gram-schmidt',              type: 'dual-of' },
  { from: 'dot-and-inner-products',  to: 'adjoints-and-transposes',   type: 'prereq' },
  { from: 'adjoints-and-transposes', to: 'orthogonal-transformations',type: 'prereq' },
  { from: 'orthogonal-transformations',to: 'qr-decomposition',        type: 'related' },

  // ── Ch 6 internal ──────────────────────────────────────────────────────────
  { from: 'orthogonal-complements',      to: 'orthogonal-projections',        type: 'prereq' },
  { from: 'orthogonal-projections',      to: 'geometric-fundamental-theorem', type: 'prereq' },
  { from: 'fundamental-theorem',         to: 'geometric-fundamental-theorem', type: 'generalizes' },
  { from: 'geometric-fundamental-theorem',to: 'least-squares',                type: 'prereq' },
  { from: 'least-squares',              to: 'regularized-least-squares',      type: 'generalizes' },

  // ── Ch 7 internal ──────────────────────────────────────────────────────────
  { from: 'first-order-systems',  to: 'coupled-systems',       type: 'prereq' },
  { from: 'coupled-systems',      to: 'eigenvectors',          type: 'prereq' },
  { from: 'eigenvectors',         to: 'simple-diagonalization',type: 'prereq' },
  { from: 'simple-diagonalization',to: 'matrix-exponentials',  type: 'prereq' },
  { from: 'matrix-exponentials',  to: 'higher-order-equations',type: 'applies-to' },
  { from: 'higher-order-equations',to: 'basis-solutions',      type: 'prereq' },

  // ── Ch 8 internal ──────────────────────────────────────────────────────────
  { from: 'eigenvectors',         to: 'complex-eigenvalues',   type: 'generalizes' },
  { from: 'eigenvectors',         to: 'jordan-form',           type: 'prereq' },
  { from: 'complex-eigenvalues',  to: 'repeated-eigenvalues',  type: 'related' },
  { from: 'repeated-eigenvalues', to: 'jordan-form',           type: 'prereq' },
  { from: 'jordan-form',          to: 'finding-jordan-form',   type: 'prereq' },
  { from: 'finding-jordan-form',  to: 'computing-eigenvalues', type: 'related' },

  // ── Ch 9 internal ──────────────────────────────────────────────────────────
  { from: 'iteration',             to: 'dominance-convergence', type: 'prereq' },
  { from: 'dominance-convergence', to: 'perron-frobenius',      type: 'prereq' },
  { from: 'perron-frobenius',      to: 'symmetric-spectra',     type: 'related' },
  { from: 'symmetric-spectra',     to: 'consensus',             type: 'applies-to' },

  // ── Ch 10 internal ─────────────────────────────────────────────────────────
  { from: 'spheres-ellipsoids', to: 'polar-decomposition', type: 'prereq' },
  { from: 'polar-decomposition',to: 'svd-form',            type: 'prereq' },
  { from: 'svd-form',           to: 'svd-invariance',      type: 'prereq' },

  // ── Ch 11 internal ─────────────────────────────────────────────────────────
  { from: 'covariance',              to: 'principal-components',   type: 'prereq' },
  { from: 'principal-components',    to: 'pca-optimality',         type: 'prereq' },
  { from: 'pca-optimality',          to: 'pca-preprocessing',      type: 'related' },
  { from: 'pca-preprocessing',       to: 'statistical-significance',type: 'related' },
  { from: 'statistical-significance',to: 'beyond-linear-pca',      type: 'prereq' },

  // ── Ch 12 internal ─────────────────────────────────────────────────────────
  { from: 'optimal-low-rank',    to: 'low-rank-in-practice', type: 'prereq' },
  { from: 'low-rank-in-practice',to: 'scaling-algorithms',   type: 'prereq' },
  { from: 'scaling-algorithms',  to: 'matrix-completion',    type: 'related' },
  { from: 'matrix-completion',   to: 'robust-factorization', type: 'related' },

  // ── Ch 13 internal ─────────────────────────────────────────────────────────
  { from: 'beyond-linear',      to: 'network-architecture', type: 'prereq' },
  { from: 'network-architecture',to: 'backpropagation',     type: 'prereq' },
  { from: 'backpropagation',    to: 'sgd',                  type: 'prereq' },
  { from: 'sgd',                to: 'attention-transformers',type: 'related' },

  // ── Cross-chapter links ────────────────────────────────────────────────────
  { from: 'rank-and-nullity',         to: 'rank-and-conditioning',   type: 'related' },
  { from: 'similarity',               to: 'eigenvectors',            type: 'prereq' },
  { from: 'gram-schmidt',             to: 'orthogonal-projections',  type: 'related' },
  { from: 'qr-decomposition',         to: 'least-squares',           type: 'applies-to' },
  { from: 'symmetric-spectra',        to: 'principal-components',    type: 'prereq' },
  { from: 'eigenvectors',             to: 'svd-form',                type: 'prereq' },
  { from: 'svd-form',                 to: 'principal-components',    type: 'prereq' },
  { from: 'svd-form',                 to: 'optimal-low-rank',        type: 'prereq' },
  { from: 'covariance',               to: 'svd-form',                type: 'related' },
  { from: 'orthogonal-transformations',to: 'svd-form',               type: 'prereq' },
  { from: 'polar-decomposition',      to: 'eigenvectors',            type: 'related' },
  { from: 'simple-diagonalization',   to: 'computing-eigenvalues',   type: 'related' },
  { from: 'iteration',                to: 'matrix-exponentials',     type: 'related' },
  { from: 'bases',                    to: 'gram-schmidt',            type: 'related' },

  // ── Application edges ──────────────────────────────────────────────────────
  { from: 'linear-systems',            to: 'network-flows',          type: 'applies-to' },
  { from: 'linear-systems',            to: 'structural-analysis',    type: 'applies-to' },
  { from: 'euclidean-transformations', to: 'computer-graphics',      type: 'applies-to' },
  { from: 'euclidean-transformations', to: 'robotic-kinematics',     type: 'applies-to' },
  { from: 'linear-transformation-defs',to: 'computer-graphics',      type: 'applies-to' },
  { from: 'dot-and-inner-products',    to: 'signal-processing',      type: 'applies-to' },
  { from: 'orthogonal-transformations',to: 'signal-processing',      type: 'applies-to' },
  { from: 'least-squares',             to: 'structural-analysis',    type: 'applies-to' },
  { from: 'least-squares',             to: 'svm',                    type: 'applies-to' },
  { from: 'first-order-systems',       to: 'power-grid',             type: 'applies-to' },
  { from: 'first-order-systems',       to: 'chemical-networks',      type: 'applies-to' },
  { from: 'matrix-exponentials',       to: 'building-temperature',   type: 'applies-to' },
  { from: 'matrix-exponentials',       to: 'vehicle-suspension',     type: 'applies-to' },
  { from: 'eigenvectors',              to: 'quantum-measurement',    type: 'applies-to' },
  { from: 'eigenvectors',              to: 'spectral-graph-theory',  type: 'applies-to' },
  { from: 'iteration',                 to: 'pagerank',               type: 'applies-to' },
  { from: 'perron-frobenius',          to: 'pagerank',               type: 'applies-to' },
  { from: 'spectral-graph-theory',     to: 'pagerank',               type: 'related' },
  { from: 'spectral-graph-theory',     to: 'image-segmentation',     type: 'applies-to' },
  { from: 'consensus',                 to: 'sensor-networks',        type: 'applies-to' },
  { from: 'svd-form',                  to: 'text-embeddings',        type: 'applies-to' },
  { from: 'svd-form',                  to: 'latent-semantic-analysis',type: 'applies-to' },
  { from: 'svd-form',                  to: 'image-processing',       type: 'applies-to' },
  { from: 'signal-processing',         to: 'image-processing',       type: 'related' },
  { from: 'tensors',                   to: 'beyond-linear-pca',      type: 'related' },
  { from: 'principal-components',      to: 'eigenfaces',             type: 'applies-to' },
  { from: 'principal-components',      to: 'neural-decoding',        type: 'applies-to' },
  { from: 'principal-components',      to: 'latent-semantic-analysis',type: 'applies-to' },
  { from: 'principal-components',      to: 'k-means',                type: 'related' },
  { from: 'principal-components',      to: 'anomaly-detection',      type: 'applies-to' },
  { from: 'pca-optimality',            to: 'k-means',                type: 'related' },
  { from: 'low-rank-in-practice',      to: 'netflix-prize',          type: 'applies-to' },
  { from: 'matrix-completion',         to: 'netflix-prize',          type: 'applies-to' },
  { from: 'latent-semantic-analysis',  to: 'text-embeddings',        type: 'related' },
  { from: 'robust-factorization',      to: 'anomaly-detection',      type: 'applies-to' },
  { from: 'beyond-linear-pca',         to: 'anomaly-detection',      type: 'applies-to' },
  { from: 'low-rank-in-practice',      to: 'image-processing',       type: 'applies-to' },
  { from: 'network-architecture',      to: 'cnns',                   type: 'applies-to' },
  { from: 'backpropagation',           to: 'cnns',                   type: 'applies-to' },
  { from: 'sgd',                       to: 'cnns',                   type: 'applies-to' },
  { from: 'attention-transformers',    to: 'llms',                   type: 'applies-to' },
  { from: 'tensors',                   to: 'cnns',                   type: 'related' },
  { from: 'eigenfaces',                to: 'neural-decoding',        type: 'related' },
  { from: 'neural-decoding',           to: 'cnns',                   type: 'related' },
];

// Back-compat alias — legacy code still imports `EDGES`. New code should use MANUAL_EDGES
// or the unioned set from concepts.index.ts.
export const EDGES: Edge[] = MANUAL_EDGES;
